name = "charge"
version = "1.1.1"
target = "javascript"

description = "A composable static site generator for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "sftsrv", repo = "charge" }
links = [{ title = "me", href = "https://nabeelvalley.co.za" }]

[documentation]
pages = [
    { title = "Getting Started", path = "getting-started.html", source = "./docs/getting-started.md" }
]

[javascript]
runtime = "node"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.6.0 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 2.0.1 and < 3.0.0"
parz = ">= 1.1.0 and < 2.0.0"
yamleam = ">= 1.0.0 and < 2.0.0"
clip = ">= 1.2.0 and < 2.0.0"
argv = ">= 1.1.0 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
glentities = ">= 6.2.1 and < 7.0.0"
mellie = ">= 2.0.0 and < 3.0.0"

